# Generated by Django 5.1.4 on 2025-01-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tematica", models.CharField(max_length=50)),
                ("pregunta", models.TextField()),
                ("respondida", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
